### ISSUE TITLE
SSL Inspection issue on tool

### ISSUE THREAD

**Issue by pratik121292** [d3ward/toolz#114]
### Context
**Browser**: Google Chrome
**OS**: Windows
**Adblock Solution**(if any):  Zscaler ZIA 

**Description of Issue**:

Our customer uses Zscaler ZIA to block ads. We were successfully able to block all the destination URLs and shows a successful result in this tool,  but only if we disable SSL inspection.
If SSL inspection is enabled, the destinations are blocked in the Zscaler logs, but doesn't show blocked in this tool.

Is SSL inspection an issue while working on this tool.

**Screenshots:**

[Attach screenshots here if applicable]

### Logs

**Test Result:**
[Describe the result of the test]

**Test Log:**
[Include the test log if available]

**Dev Console:**
[Copy and paste any relevant logs or error messages from the developer console]

### Confirmation
- [ ] I confirm that I have filled out all the necessary fields with enough detail to allow for the proper investigation and potential resolution of the issue.

**Comment by d3ward** [comment]
When SSL inspection is enabled, the test may not be able to detect blocked hosts because the traffic is decrypted and re-encrypted by your product (the SSL inspection). This process may alter the traffic in a way that makes it difficult for the test tool to accurately log whether ads/hosts are being blocked, my tool is not designed to recognise or handle traffic that has been altered by SSL inspection. Unfortunately, this is a browser/Javascript limitation. 

This test has a compatibility table, and I think it's better to tell your customers that they can run the test with SSL temporarily disabled, and explain to them that with SSL enabled, the test just can't detect blocked, but that doesn't mean it wasn't blocked.
