### ISSUE TITLE
problem with adblock version

### ISSUE THREAD

**Issue by vjrmy** [d3ward/toolz#37]
I use Mull Browser with Ublock Origin and use [compressed adblock version](https://raw.githubusercontent.com/d3ward/toolz/master/src/d3host.adblock) then i test but the result 98% 
`https://advice-ads.s3.amazonaws.com`
`https://ads.facebook.com`
This two links are not blocked. Is this my problem or your filter adblock?

**Comment by d3ward** [comment]
Hello , 98% is a pretty good result! 
The reason the test doesn't show these two can be many ...
- The test adblock is supposed to work better on chromium based browsers with more precise results sometimes on Safari or Firefox based we may have false negative/positive
- DNS sometimes can mess up with the test because not all  dns services return an error "blocked by dns/adblock" like ubock do 

This being said if you are using the list then you are doing 100% just we have that limitations . 

In the next weeks I plan to release v2 of the test adblock that brings some improvements on UI , and testing process with some new features too . I'm also including a table with all scenarios tests and browser support to explain that in some environment the test will give some false negative results. 

So to answer your question the issue is not you or the filter adblock but the test limitations on browser . 
Let me know if you have more questions
