### ISSUE TITLE
Weird behaviour(kiwi+uBO)

### ISSUE THREAD

**Issue by kryptobolt200528** [d3ward/toolz#63]
https://github.com/d3ward/toolz/assets/72438196/9d435fcb-fd20-4910-a957-7a516869bea1

**Comment by iam-py-test** [comment]
Kiwi browser is not supported by uBlock Origin. You need to use Firefox Mobile.

**Comment by kryptobolt200528** [comment]
> Kiwi browser is not supported by uBlock Origin. You need to use Firefox Mobile.

it works really well with kiwi,just like the way it does with firefox mobile

**Comment by iam-py-test** [comment]
Just because it works now doesn't mean it will work in the future. [Kiwi is not](https://github.com/uBlockOrigin/uAssets/issues/12280#issuecomment-1068996982) [supported by](https://github.com/uBlockOrigin/uAssets/issues/15535#issuecomment-1303009830) [uBlock Origin](https://github.com/uBlockOrigin/uAssets/issues/17547#issuecomment-1505384423), [and does not](https://github.com/uBlockOrigin/uAssets/issues/15935#issuecomment-1340419744) [work properly](https://github.com/uBlockOrigin/uAssets/issues/15143#issuecomment-1266624525).
Additionally, 
- [Kiwi browser has it's own content blocker which is known to conflict with uBo (to disable it, you have to uncheck "Hide annoying ads").](https://github.com/uBlockOrigin/uAssets/issues/15194#issuecomment-1272343226)
- [Kiwi browser disables](https://www.reddit.com/r/uBlockOrigin/comments/10xntsr/comment/j7teo9p/) [content blockers](https://github.com/uBlockOrigin/uAssets/issues/11309#issuecomment-1013101613) [on random pages](https://github.com/kiwibrowser/src/blob/c51d640a8e984ff0fb24049c53a7ed4e458775ef/extensions/browser/api/web_request/web_request_permissions.cc#L167) and [isn't updated that frequently](https://github.com/kiwibrowser/src/commits/master).
- [Also, tests like this aren't very reliable, and even uBlock Origin's developer recommends against them](https://archive.is/V9GnQ)

**Comment by d3ward** [comment]
@iam-py-test 
- That's right, disabling the built-in reduce the conflict. 
- I see you linked to the old topic and repo from kiwibrowser. The new one is https://github.com/kiwibrowser/src.next and has no whitelist anymore ( except bing and kiwi servers ) and has been updated (especially the security ones, last update 18 apr 2023, but also more updates != more security, it's a complex topic). And the privacy policy of Kiwi is the best one so far compared "others" ...
- I agree the test is not so reliable, with chromium it works 99% with the most common blocking solution, with firefox there are problems ( like the linked screenshot) because ubo works differently there (adding a rule like @@*$redirect-rule makes the test work as expected).

Also the extension on Kiwi is not something official, it's a bridging feature implemented by 1 developer, overall it's solid and does not guarantee 100% compatibility but ubo works pretty well on Kiwi , there are just some very small issues though

@kryptobolt200528 Looks like a cache issue mostly , from the video you shared, when you clear cache and get a low % on the test , the test kind of fails, and a reload fixes it . I'll try to address this specifically with next update .

**Comment by iam-py-test** [comment]
> I see you linked to the old topic and repo from kiwibrowser. The new one is https://github.com/kiwibrowser/src.next and has no whitelist anymore ( except bing and kiwi servers ) and has been updated (especially the security ones, last update 18 apr 2023, but also more updates != more security, it's a complex topic). And the privacy policy of Kiwi is the best one so far compared "others" ...

Oh, didn't realize. Sorry.

**Comment by kryptobolt200528** [comment]
i would like to highlight that your previous version of the test ran fine everytime.
